# Generated by Django 4.2.2 on 2023-08-06 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0002_alter_conversationmessage_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversationmessage',
            old_name='Conversation',
            new_name='conversation',
        ),
    ]
