# Generated by Django 4.2.2 on 2023-06-19 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='nombre',
            new_name='Item',
        ),
    ]
