# Generated by Django 4.2.2 on 2023-06-19 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_rename_nombre_item_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Item',
            new_name='name',
        ),
    ]
